apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prefect-statefulset
  namespace: dev
spec:
  selector:
    matchLabels:
      app: prefect
  serviceName: prefect-service
  replicas: 1
  template:
    metadata:
      labels:
        app: prefect
    spec:
      containers:
      - name: prefect
        image: marquard/prefect-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4200
          name: prefect-api
        resources:
          requests:
            memory: 500Mi
          limits:
            memory: 2Gi
  volumeClaimTemplates:
  - metadata:
      name: prefect-storage
      namespace: dev
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prefect-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: prefect
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prefect-ingress
  namespace: dev
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
  - host: k3.prefect.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prefect-service
            port:
              number: 4200

